[package]
name = "terminal-io"
version = "0.1.0"
authors = ["Aimeri Baddouh <aimeri@baddouh.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subprocess = "0.2.4"
